name: CI/CD Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build and test steps here
      # For example:
      - name: Build and Test
        run: |
        echo "push or PR on master branch"
      

