name: Print Push/Pull Request Event

on:
  push:
  pull_request:
  pull_request_target:
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  print_event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print event type
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Push event happened"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Pull request event happened"
          elif [ "${{ github.event_name }}" == "pull_request_target" ]; then
            echo "Pull request event for target repository happened"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual workflow_dispatch event happened"
          else
            echo "Unknown event happened"
          fi
